# Generated by Django 4.2.11 on 2024-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='컨텐츠')),
                ('content_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
