# Generated by Django 4.2.11 on 2025-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='In_Iris_21_0_4',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_0_5',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_2_3',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_3_10',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_3_8',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_3_9',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_4_3',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_4_4',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_5_6',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_5_7',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_5_8',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_6_6',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_6_7',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_7_5',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_7_6',
        ),
        migrations.DeleteModel(
            name='In_Iris_21_8_2',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_3',
            old_name='research_project_number',
            new_name='res_num',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='content_1',
            new_name='content_1_en',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='content_2',
            new_name='content_1_kr',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='content_3',
            new_name='content_2_en',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='content_4',
            new_name='content_2_kr',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='content_5',
            new_name='content_3_en',
        ),
        migrations.RenameField(
            model_name='in_iris_21_1_5',
            old_name='language',
            new_name='content_3_kr',
        ),
        migrations.RenameField(
            model_name='in_iris_21_2_1',
            old_name='change_reason',
            new_name='annual',
        ),
        migrations.RenameField(
            model_name='in_iris_21_2_1',
            old_name='step_selection',
            new_name='previous_annual',
        ),
        migrations.RenameField(
            model_name='in_iris_21_2_1',
            old_name='announcement_period',
            new_name='res_num',
        ),
        migrations.RenameField(
            model_name='in_iris_21_2_2',
            old_name='research_project_number',
            new_name='res_num',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_1',
            old_name='entrusted_research_development_institution',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_1',
            old_name='entrusted_research_approval',
            new_name='radio_selection',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_1',
            old_name='joint_research_development_institution',
            new_name='research_development_institution_name',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_2',
            old_name='business_registration_number',
            new_name='execution_classification',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_2',
            old_name='radio_selection',
            new_name='participation_annual',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_2',
            old_name='company_type',
            new_name='practitioner',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_2',
            old_name='establishment_classification',
            new_name='representative',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_2',
            old_name='nationality',
            new_name='research_responsible_person',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_3',
            old_name='execution_classification',
            new_name='annual',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_3',
            old_name='participation_annual',
            new_name='equipment_integration',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_3',
            old_name='participation_annual_2',
            new_name='exception_reason_for_regulation_application',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_3',
            old_name='practitioner',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_4',
            old_name='research_development_institution_name',
            new_name='account_holder',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_4',
            old_name='annual',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_4',
            old_name='institution_role',
            new_name='bank_classification',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_4',
            old_name='equipment_integration',
            new_name='research_funding_account_change_1',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_4',
            old_name='exception_reason_for_regulation_application',
            new_name='research_funding_account_change_2',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_5',
            old_name='research_funding_account_change_1',
            new_name='ethics_agreement_date',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_5',
            old_name='account_number',
            new_name='ethics_guide_provided',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_5',
            old_name='bank_classification',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_5',
            old_name='research_funding_account_change_2',
            new_name='participation_phase_1',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='ethics_guide_provided',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='name',
            new_name='personnel_name',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='new_recruit_type',
            new_name='personnel_role',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='performance_type',
            new_name='power_of_attorney',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='ethics_agreement_date',
            new_name='support_year_1',
        ),
        migrations.RenameField(
            model_name='in_iris_21_3_7',
            old_name='participation_phase_1',
            new_name='support_year_2',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_1',
            old_name='related_institution_change',
            new_name='radio_selection',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_1',
            old_name='support_institution_removal',
            new_name='support_year_1',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_2',
            old_name='account_number',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_2',
            old_name='bank_classification',
            new_name='participation_type',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_2',
            old_name='business_registration_number',
            new_name='personnel_name',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_2',
            old_name='company_type',
            new_name='personnel_role',
        ),
        migrations.RenameField(
            model_name='in_iris_21_4_2',
            old_name='execution_type',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_1',
            old_name='participating_institution',
            new_name='government_cash_funding',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_1',
            old_name='task_phase',
            new_name='government_funding_ratio',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_1',
            old_name='task_year',
            new_name='institution_cash_contribution',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_5',
            old_name='difference_cash',
            new_name='cash',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_5',
            old_name='difference_in_kind',
            new_name='deposit_amount',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_5',
            old_name='difference_subtotal',
            new_name='in_kind',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_5',
            old_name='itemized_funding_cash',
            new_name='round_number',
        ),
        migrations.RenameField(
            model_name='in_iris_21_5_5',
            old_name='itemized_funding_in_kind',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_2',
            old_name='installation_location_change',
            new_name='radio_selection',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='installation_location',
            new_name='annual_operating_cost',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='ownership_type',
            new_name='dedicated_personnel_count',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='owning_institution',
            new_name='in_kind_contribution_reflected',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='utilization_period',
            new_name='operation_end_date',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='specifications',
            new_name='sequence_number',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_3',
            old_name='quantity',
            new_name='utilization_plan',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_4',
            old_name='annual_operating_cost',
            new_name='construction_cost_unit_kkr',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_4',
            old_name='dedicated_personnel_count',
            new_name='construction_timing',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_4',
            old_name='in_kind_contribution_reflected',
            new_name='estimated_price_unit_kkr',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_4',
            old_name='research_facility_equipment_name',
            new_name='manufacturer_name',
        ),
        migrations.RenameField(
            model_name='in_iris_21_6_4',
            old_name='utilization_plan',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='in_iris_21_7_1',
            old_name='performance_target_indicator',
            new_name='radio_selection',
        ),
        migrations.RenameField(
            model_name='in_iris_21_7_3',
            old_name='performance_indicator_name',
            new_name='evaluation_item_main_performance',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_1',
            name='research_project_number',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='annual',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='months',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='previous_annual',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='previous_step',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='research_development_end_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='research_development_start_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_2_2',
            name='step',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_1',
            name='joint_research_approval',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_1',
            name='joint_research_notice',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_1',
            name='main_research_approval',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_1',
            name='main_research_development_institution',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_1',
            name='research_institution_info_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_2',
            name='location',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_2',
            name='research_development_payment_type',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_3',
            name='government_support',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_3',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_3',
            name='research_responsible_person',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_4',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_4',
            name='participation_status',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_4',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_4',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_4',
            name='student_integration',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_5',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_5',
            name='agreement_institution',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='entrusted_research_institution_leader',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='joint_research_institution_leader',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='joint_research_institution_leader_notice',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='main_research_institution_leader',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='research_support_personnel_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='research_support_staff_change_notice',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_6',
            name='researcher_change_notice',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_7',
            name='participation_phase_2',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_7',
            name='position_status',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_7',
            name='recruitment_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_7',
            name='role',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_3_7',
            name='supporting_documents',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_4_2',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_4_2',
            name='institution_role',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_4_2',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_4_2',
            name='supporting_institution_name',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_4_2',
            name='supporting_institution_role_description',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_2',
            name='project_budget_transfer',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_2',
            name='research_institution_funding_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_2',
            name='total_research_budget_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='government_cash_funding',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='government_funding_ratio',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='institution_cash_contribution',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='institution_contribution_ratio',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='institution_in_kind_contribution',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='institution_in_kind_ratio',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='institution_total_contribution',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_3',
            name='total_in_kind',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='indirect_cost_decrease',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='indirect_cost_increase',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='integrated_research_facility_equipment',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='international_research_budget_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='international_research_budget_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='labor_cost_cash_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='labor_cost_cash_change_nonprofit',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='labor_cost_in_kind_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='labor_cost_nonprofit_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='other_budget_items_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='overseas_researcher_support_fund_increase',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_allowance_decrease',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_allowance_increase',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_facility_equipment_cost_high',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_facility_equipment_cost_low',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_facility_equipment_cost_very_high',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='research_lab_operation_plan_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='security_allowance_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_4',
            name='subcontracted_research_budget_increase',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_5',
            name='itemized_funding_subtotal',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_5',
            name='total_funding_cash',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_5',
            name='total_funding_in_kind',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_5',
            name='total_funding_subtotal',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_5_5',
            name='unpaid_salary_baseline',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_2',
            name='research_facility_equipment_status_change',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_3',
            name='radio_selection',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_3',
            name='usage_purpose',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_4',
            name='operation_end_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_4',
            name='operation_start_date',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_5',
            name='facility_equipment_plan_change_above_30M',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_5',
            name='facility_equipment_plan_change_below_30M',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_5',
            name='facility_equipment_plan_change_within_20_percent',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_6_5',
            name='installation_location_change_new_plan',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_7_2',
            name='mandatory_status',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_7_2',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_7_4',
            name='performance_target_metric',
        ),
        migrations.RemoveField(
            model_name='in_iris_21_8_1',
            name='revenue_commitment_share_change',
        ),
        migrations.AddField(
            model_name='in_iris_21_1_5',
            name='content_4_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_1_5',
            name='content_4_kr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_1_5',
            name='content_5_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_1_5',
            name='content_5_kr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_1',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_1',
            name='previous_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_1',
            name='step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_2',
            name='change_item',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_2',
            name='research_development_content',
            field=models.TextField(blank=True, max_length=1333, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_2',
            name='research_development_performance',
            field=models.TextField(blank=True, max_length=1333, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_2_2',
            name='utilization_plan_and_expected_effect',
            field=models.TextField(blank=True, max_length=1333, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='company_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='establishment_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='institution_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_1',
            name='research_development_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_2',
            name='government_support',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_2',
            name='participation_annual_2',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_3',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_3',
            name='participation_status',
            field=models.CharField(choices=[('Participating', 'Participating'), ('Not Participating', 'Not Participating')], default='Not Participating', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_3',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_3',
            name='student_integration',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_4',
            name='agreement_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='new_recruit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='participation_phase_2',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='participation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='performance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='position_status',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='radio_selection',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='recruitment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='researcher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_5',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/'),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='calculated_annual_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='cash_budget_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='in_kind_budget_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='major_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='part_time_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='participation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='participation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='participation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='participation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='participation_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='researcher_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='sequence_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_6',
            name='unpaid_budget_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_3_7',
            name='representative_credit_info_consent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='bank_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='company_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='execution_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='institution_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='support_year_2',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='supporting_institution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_4_1',
            name='supporting_institution_role_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='institution_contribution_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='institution_in_kind_contribution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='institution_in_kind_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='institution_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='institution_total_contribution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='research_institution_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='total_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='total_cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='total_in_kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_1',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='difference_cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='difference_in_kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='difference_subtotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='institution_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='itemized_funding_cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='itemized_funding_in_kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='itemized_funding_subtotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='research_institution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='total_funding_cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='total_funding_in_kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='total_funding_subtotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='unpaid_salary_baseline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_2',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='in_kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='research_funds_by_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='sub_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='subtotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_4',
            name='unpaid_salary_baseline_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_5',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_5',
            name='research_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_5_5',
            name='research_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='installation_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='owning_institution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='research_facility_equipment_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='specifications',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='usage_purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_2',
            name='utilization_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_3',
            name='operation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/'),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='radio_selection',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='shared_usage_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='specifications',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_4',
            name='usage_purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='annual_operating_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='change_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='construction_cancellation_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='dedicated_personnel_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='installation_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='operation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='operation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='research_facility_equipment_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='sequence_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='utilization_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_6_5',
            name='utilization_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_1',
            name='mandatory_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_1',
            name='performance_indicator_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_1',
            name='target_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_1',
            name='total_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_1',
            name='weight_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='pre_research_domestic_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='pre_research_domestic_performance_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='target_achievement_basis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='world_top_level_country_institution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_3',
            name='world_top_level_performance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_4',
            name='evaluation_environment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_4',
            name='evaluation_item_main_performance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_7_4',
            name='evaluation_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='commercialization_performance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='detailed_performance_indicator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='institution_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='round_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='round_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='round_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='round_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='round_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='in_iris_21_8_1',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='in_iris_21_5_5',
            name='research_institution_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
