# Generated by Django 4.2.11 on 2024-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='content_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
