# Generated by Django 4.2.11 on 2024-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0002_alter_data_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='content_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
