# Generated by Django 4.2.11 on 2024-12-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0003_remove_data_id_alter_data_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('table_type', models.CharField(max_length=50)),
                ('title_1', models.CharField(max_length=50)),
                ('checke_1', models.CharField(max_length=10)),
                ('title_2', models.CharField(max_length=50)),
                ('checke_2', models.CharField(max_length=10)),
                ('title_3', models.CharField(max_length=50)),
                ('checke_3', models.CharField(max_length=10)),
                ('title_4', models.CharField(max_length=50)),
                ('checke_4', models.CharField(max_length=10)),
                ('title_5', models.CharField(max_length=50)),
                ('checke_5', models.CharField(max_length=10)),
                ('title_6', models.CharField(max_length=50)),
                ('checke_6', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'RCMS_2',
            },
        ),
    ]
