# Generated by Django 4.2.11 on 2024-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0004_rcms_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_1',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_2',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_3',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_4',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_5',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='checke_6',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='table_type',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_5',
        ),
        migrations.RemoveField(
            model_name='rcms_2',
            name='title_6',
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='assort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='create_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='upload_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='views',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='rcms_2',
            table='RCMS_3',
        ),
    ]
