# Generated by Django 4.2.11 on 2024-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0005_remove_rcms_2_checke_1_remove_rcms_2_checke_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_file', models.CharField(blank=True, max_length=50, null=True)),
                ('writer', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
                ('views', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_3',
            },
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='assort',
            new_name='call_num',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='create_date',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='num',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='title',
            new_name='national_researcher_number',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='upload_file',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='views',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='rcms_2',
            old_name='writer',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='address_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='certification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_1',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_2',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_3',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_4',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_5',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='checke_6',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='table_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_5',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='title_6',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_address_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='unreg_org_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rcms_2',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='rcms_2',
            table='RCMS_2',
        ),
    ]
