# Generated by Django 4.2.11 on 2024-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0007_rcms_3_1_rcms_3_2_delete_rcms_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_file', models.CharField(blank=True, max_length=50, null=True)),
                ('writer', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
                ('views', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_4',
            },
        ),
    ]
