# Generated by Django 4.2.11 on 2024-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0008_rcms_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcms_4',
            name='upload_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
