# Generated by Django 4.2.11 on 2024-12-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0010_rcms_5_1_rcms_5_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_6_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_1',
            },
        ),
        migrations.CreateModel(
            name='Rcms_6_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_2',
            },
        ),
        migrations.CreateModel(
            name='Rcms_6_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_3',
            },
        ),
        migrations.CreateModel(
            name='Rcms_6_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_4',
            },
        ),
        migrations.CreateModel(
            name='Rcms_6_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_5',
            },
        ),
        migrations.CreateModel(
            name='Rcms_6_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('external_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_6_6',
            },
        ),
    ]
