# Generated by Django 4.2.11 on 2024-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0011_rcms_6_1_rcms_6_2_rcms_6_3_rcms_6_4_rcms_6_5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('assign_name', models.CharField(blank=True, max_length=50, null=True)),
                ('step_annual', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('dev_period', models.CharField(blank=True, max_length=50, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('host_rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_1',
            },
        ),
        migrations.CreateModel(
            name='Rcms_8_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('app_category', models.CharField(blank=True, max_length=100, null=True)),
                ('host_rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('current_dev_period', models.CharField(blank=True, max_length=50, null=True)),
                ('total_dev_period', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('agree_class', models.CharField(blank=True, max_length=50, null=True)),
                ('settle_form', models.CharField(blank=True, max_length=50, null=True)),
                ('rnd_cost_payment_assort', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_agree_status', models.CharField(blank=True, max_length=50, null=True)),
                ('execute_status', models.CharField(blank=True, max_length=50, null=True)),
                ('research_fund_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_2',
            },
        ),
        migrations.CreateModel(
            name='Rcms_8_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('step', models.CharField(blank=True, max_length=100, null=True)),
                ('annual', models.CharField(blank=True, max_length=50, null=True)),
                ('part_class', models.CharField(blank=True, max_length=50, null=True)),
                ('rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('rnd_cost_payment_assort', models.CharField(blank=True, max_length=50, null=True)),
                ('total_cash_1', models.CharField(blank=True, max_length=50, null=True)),
                ('total_kind_1', models.CharField(blank=True, max_length=50, null=True)),
                ('gov_sup_rnd_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_rnd_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_rnd_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('local_gov_rnd_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('local_gov_rnd_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('total_cash_2', models.CharField(blank=True, max_length=50, null=True)),
                ('total_kind_2', models.CharField(blank=True, max_length=50, null=True)),
                ('direct_cost_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('direct_cost_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('indirect_cost_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('indirect_cost_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('commission_rnd_cash', models.CharField(blank=True, max_length=50, null=True)),
                ('commission_rnd_kind', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_3_1',
            },
        ),
    ]
