# Generated by Django 4.2.11 on 2024-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0012_rcms_8_1_rcms_8_2_rcms_8_3_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcms_8_1',
            name='flag_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rcms_8_1',
            name='flag_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rcms_8_1',
            name='flag_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
