# Generated by Django 4.2.11 on 2024-12-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0013_rcms_8_1_flag_1_rcms_8_1_flag_2_rcms_8_1_flag_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_3_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('business_reg_num', models.CharField(blank=True, max_length=100, null=True)),
                ('rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('rnd_cost_payment_assort', models.CharField(blank=True, max_length=50, null=True)),
                ('participate_assort', models.CharField(blank=True, max_length=50, null=True)),
                ('non_profit', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('research_fund_account', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_whether', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('innovation_act_whether', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_leave_report', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_3_2',
            },
        ),
    ]
