# Generated by Django 4.2.11 on 2024-12-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0014_rcms_8_3_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_3_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('rnd_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('participate_assort', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('foreign_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('labor_cost_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_3_3',
            },
        ),
    ]
