# Generated by Django 4.2.11 on 2024-12-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0015_rcms_8_3_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcms_8_3_3',
            name='employ_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
