# Generated by Django 4.2.11 on 2024-12-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0016_rcms_8_3_3_employ_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_3_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('inst', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_role', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('res_fund_execute_auth', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_3_4',
            },
        ),
    ]
