# Generated by Django 4.2.11 on 2025-01-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0017_rcms_8_3_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('part_class', models.CharField(blank=True, max_length=50, null=True)),
                ('res_fund_execute_auth', models.CharField(blank=True, max_length=50, null=True)),
                ('whether_use', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('whether_receive', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_4',
            },
        ),
    ]
