# Generated by Django 4.2.11 on 2025-01-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0018_rcms_8_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('assort', models.CharField(blank=True, max_length=50, null=True)),
                ('card_company', models.CharField(blank=True, max_length=50, null=True)),
                ('card_num', models.CharField(blank=True, max_length=50, null=True)),
                ('validity_period', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_account_num', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_status', models.CharField(blank=True, max_length=50, null=True)),
                ('whether_reg', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_5',
            },
        ),
    ]
