# Generated by Django 4.2.11 on 2025-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcms', '0019_rcms_8_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcms_8_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
                ('tab_title', models.CharField(max_length=50)),
                ('issue_date', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('req_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('virtual_account_num', models.CharField(blank=True, max_length=50, null=True)),
                ('depositor', models.CharField(blank=True, max_length=50, null=True)),
                ('process_status', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit_date', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit_deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('request_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('refusal_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_exclusion_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RCMS_8_6',
            },
        ),
    ]
